export enum DocumentType {
  INVOICE = 'INVOICE',
  PAYMENT_RECEIPT = 'PAYMENT_RECEIPT',
  DELIVERY_RECEIPT = 'DELIVERY_RECEIPT',
  EXPENSE_RECEIPT = 'EXPENSE_RECEIPT',
  REFUND_RECEIPT = 'REFUND_RECEIPT'
} 