export enum FeedType {
  // Arvines Feeds
  BROILER_STARTER_MP = 'BROILER_STARTER_MP',
  BROILER_STARTER_MV = 'BROILER_STARTER_MV',
  BROILER_GROWER_MP = 'BROILER_GROWER_MP',
  BROILER_GROWER_MV = 'BROILER_GROWER_MV',

  // Silverland Feeds
  BROILER_STARTER = 'BROILER_STARTER',
  BROILER_GROWER = 'BROILER_GROWER',
  BROILER_FINISHER = 'BROILER_FINISHER',
  LAYER_STARTER = 'LAYER_STARTER',
  LAYER_GROWER = 'LAYER_GROWER',
  COMPLETE_LAYER_MASH = 'COMPLETE_LAYER_MASH',

  // Backbone Feeds
  BACKBONE_LAYER_STARTER = 'BACKBONE_LAYER_STARTER',
  BACKBONE_LAYER_GROWER = 'BACKBONE_LAYER_GROWER',
  BACKBONE_COMPLETE_LAYER_MASH = 'BACKBONE_COMPLETE_LAYER_MASH',

  // Local Feed
  LOCAL_FEED = 'LOCAL_FEED'
} 