export enum OrderStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  ACCOUNTANT_APPROVED = 'ACCOUNTANT_APPROVED',
  MANAGER_APPROVED = 'MANAGER_APPROVED',
  APPROVED = 'APPROVED',
  CANCELLED = 'CANCELLED',
  REJECTED = 'REJECTED',
}
